import Head from "next/head";
// import { api } from "~/utils/api";

import * as React from "react"
import { Moon, Sun } from "lucide-react"
import { useTheme } from "next-themes"
import { ModeToggle } from "~/components/ModeToggle"; 

import {
  Accordion,
  AccordionContent,
  AccordionItem,
  AccordionTrigger,
} from "ComponentsUI/ui/accordion"


import { BsFillMoonStarsFill } from "react-icons/bs";
import { useState } from "react";
export default function Home() {
  const [darkMode, setDarkMode] = useState(false);

  // const hello = api.post.hello.useQuery({ text: "from tRPC" });
  // const user = useUser();
  const modeToggle = ModeToggle();
  return (
    <>
      <div className={darkMode ? 'dark' : ""}>
      <Head>
        <title>Energy sustainability at Ohio State</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico"/>
      </Head>

      <main className="flex min-h-screen flex-col items-center justify-center bg-stone-25 dark:bg-stone-900">
      <div className="flex justify-between items-center w-full px-6 top-text">
        <h1 className="text-green-800 text-5xl dark:text-green-600">Energy Sustainability at Ohio State</h1>
          <ul className="flex justify-end items-center">
          <li className="mr-10">
              <BsFillMoonStarsFill 
                onClick={() => setDarkMode(!darkMode)}
                className="cursor-pointer text-2xl text-stone-900 dark:text-stone-50"
              />
            </li>
          </ul>

        </div>
        
        <div className="bg-lime-200 dark:bg-green-800">
          <h3 className="text-5xl text-left mb-1.5 ml-24 dark:text-stone-50 mt-4">Impact Statement</h3>
          <p className="mission-text text-xl ml-20 mb-3 text-stone-900 dark:text-stone-50">Creating a sustainability dashboard for the Smart Campus Challenge can impact campus behavior by raising awareness, promoting sustainable practices, and fostering competition. It holds the university accountable, provides data for decision-making, and directly supports resource stewardship goals. Additionally, it educates and advocates for sustainability, potentially leading to collaborations and a more eco-conscious campus community.</p>
        </div>
      <p>THIS SHOULD CHANGE COLORS DEPENDING ON THEME?</p>
    {modeToggle}
    <Accordion type="single" collapsible className="w-full">
      <AccordionItem value="item-1">
        <AccordionTrigger>Is it accessible?</AccordionTrigger>
        <AccordionContent>
          Yes. It adheres to the WAI-ARIA design pattern.
        </AccordionContent>
      </AccordionItem>
      <AccordionItem value="item-2">
        <AccordionTrigger>Is it styled?</AccordionTrigger>
        <AccordionContent>
          Yes. It comes with default styles that matches the other
          components&apos; aesthetic.
        </AccordionContent>
      </AccordionItem>
      <AccordionItem value="item-3">
        <AccordionTrigger>Is it animated?</AccordionTrigger>
        <AccordionContent>
          Yes it Is animated by default, but you can disable it if you prefer.
        </AccordionContent>
      </AccordionItem>
    </Accordion>
      </main>
      </div>
    </>
  );
}
