import Head from "next/head";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="flex min-h-screen flex-col items-center justify-center bg-[#f0fdf4]">
        <div className="top-text">Sustainable practices at Ohio State</div>
        <div>
          <h1 className="text-7xl text-center mb-1.5 font-serif">Impact Statement</h1>
          <p className="mission-text text-xl">Creating a sustainability dashboard for the Smart Campus Challenge can impact campus behavior by raising awareness, promoting sustainable practices, and fostering competition. It holds the university accountable, provides data for decision-making, and directly supports resource stewardship goals. Additionally, it educates and advocates for sustainability, potentially leading to collaborations and a more eco-conscious campus community.</p>
           
        </div>
      </main>
    </>
  );
}
